[libraries]

olympus-lib = { module = "earth.terrarium.olympus:olympus-fabric-1.21.7", version = "1.5.2" }
resourceful-config = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21.7", version = "3.7.1" }
resourceful-lib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.6", version = "3.6.0" }
