[libraries]

olympus-lib = { module = "earth.terrarium.olympus:olympus-fabric-1.21.5", version = "1.3.6" }
resourceful-config = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-1.21.5", version = "3.5.15" }
resourceful-lib = { module = "com.teamresourceful.resourcefullib:resourcefullib-fabric-1.21.5", version = "3.5.0" }
